@echo off

set JMSD_CURRENT_WORKING_DIRECTORY=%cd%

cd ..
rmdir %JMSD_CURRENT_WORKING_DIRECTORY% /S /Q
mkdir %JMSD_CURRENT_WORKING_DIRECTORY%
cd %JMSD_CURRENT_WORKING_DIRECTORY%

set JMSD_CURRENT_WORKING_DIRECTORY=
